# Generated by Django 5.0.1 on 2024-02-01 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('rosted', models.CharField(max_length=50)),
                ('ingredients', models.CharField(max_length=50)),
                ('special_ingredient', models.CharField(max_length=100)),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating_counts', models.IntegerField()),
                ('imagelink_square', models.ImageField(upload_to='cafeCoffee')),
                ('imagelink_portrait', models.ImageField(upload_to='cafeCoffee')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.coffeecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=2)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.coffeeproducts')),
            ],
        ),
    ]
