# Generated by Django 5.0.1 on 2024-02-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_coffeeproducts_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeproducts',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
