# Generated by Django 5.0.1 on 2024-02-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_coffeeproducts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeproducts',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
